library(arules)
book <- read.csv("C:/Users/Suresh/Downloads/book.csv", header = T, colClasses = "factor")
rules <- apriori(book)
summary(rules)
rules <- apriori(book,parameter = list(minlen=2,maxlen=3,supp=.7))
inspect(rules)                 
library(arulesViz)
plot(rules)
plot(rules, method = "grouped")
plot(rules, method = "graph")

rules <- apriori(book,parameter = list(minlen=3,maxlen=4,supp=.7))
inspect(rules)                 
library(arulesViz)
plot(rules)
plot(rules, method = "grouped")
plot(rules, method = "graph")
rules <- apriori(book,parameter = list(minlen=3,maxlen=4,confidence = 0.05,supp=.7))
inspect(rules)                 
library(arulesViz)
plot(rules)
plot(rules, method = "grouped")
plot(rules, method = "graph")
                 