cc <- calories_consumed
summary(cc)
plot(cc$Weight.gained..grams.,cc$Calories.Consumed)
cor(cc$Calories.Consumed,cc$Weight.gained..grams.)
reg <- lm(cc$Weight.gained..grams.~cc$Calories.Consumed, data = cc)
summary(reg)
confint(reg,level = 0.95)
predict(reg,interval="confidence")
attach(cc)
reg <- lm(log(Weight.gained..grams.)~Calories.Consumed)
summary(reg)
confint(reg,level = 0.95)
predict(reg,interval="confidence")
reg <- lm(log(Weight.gained..grams.)~log(Calories.Consumed))
summary(reg)
confint(reg,level = 0.95)
predict(reg,interval="confidence")
