dt <- delivery_time
summary(dt)
plot(dt$Sorting.Time,dt$Sorting.Time)
cor(dt$Sorting.Time,dt$Delivery.Time)
hist(dt$Delivery.Time)
hist(dt$Sorting.Time)
reg <- lm(dt$Delivery.Time~dt$Sorting.Time)
summary(reg)
confint(reg,level = 0.95)
predict(reg,interval = 'confidence')
attach(dt)
reg <- lm(log(Delivery.Time)~Sorting.Time)
summary(reg)
confint(reg,level = 0.95)
predict(reg,interval = 'confidence')
reg <- lm(log(Delivery.Time)~log(Sorting.Time))
summary(reg)
confint(reg,level = 0.95)
predict(reg,interval = 'confidence')
reg <- lm(log(Delivery.Time)~log(Sorting.Time))
summary(reg)

