cd <- Computer_Data
cd <- cd[,c(-1,-7,-8,-9)]
View(cd)
summary(cd)
pairs(cd)
cor(cd)
library(corpcor)
cor2pcor(cor(cd))
attach(cd)
model.com <- lm(price~speed+hd+ram+screen+ads)
summary(model.com)
model.pr <- lm(price~speed)
summary(model.pr)
model.sp <- lm(price~speed+hd)
summary(model.pr)
model.hd <- lm(price~speed+hd+ram)
summary(model.hd)
VIF::vif(model.com)
avPlots(model.com,id.n=2,id.cex=0.7)
influence.measures(model.com)
windows()
influenceIndexPlot(model.com,id.n=3) 
influencePlot(model.com,id.n=3)
model.com <- lm(log(price)~speed+hd+ram+screen+ads)
summary(model.com)
model.com <- lm(log(price)~log(speed)+log(hd)+log(ram)+log(screen)+log(ads))
summary(model.com)
model.com <- lm((price)~log(speed)+log(hd)+log(ram)+log(screen)+log(ads))
summary(model.com)
model.com <- lm(log(price)~log(speed)+log(hd)+log(ram)+log(screen)+log(ads))
summary(model.com)